### PR TITLE
+Feature: Added darkmode toggle switch.

### PR DESCRIPTION
**Pull request by SuhailAhmedVelorum**
Added dark mode toggle functionality.

### CODE REVIEW

**Review by k4u5h1k — COMMENTED** [review]
Please change the toggle slider to something more appealing and push it further upward into the nav

**Comment by SuhailAhmedVelorum** [comment]
added 2 new vendors: jscookie and darkreader in the assets/vendor/ folder
modified 2 files: assets/js/main.js and assets/css/style.css

**Comment by SuhailAhmedVelorum** [comment]
Just confirming, you want the toggle in the nav? Also any suggestions for the slider?

**Comment by SuhailAhmedVelorum** [comment]
@k4u5h1k Suggestions added to new commit.

**Comment by PratikGarai** [comment]
Looks amazing! gg!

**Comment by SuhailAhmedVelorum** [comment]
Glad you liked it!

**Pull request merged**
